### ISSUE TITLE
app crashes on startup

### ISSUE THREAD

**Issue by voxrie** [prateek-chaubey/YTPro#1]
its not a virus, right? 😞

**Comment by prateek-chaubey** [comment]
The whole code is open source , you can search for malicious code in there.

**Comment by voxrie** [comment]
dude i know but i'm not sure with this project. can you explain how is this being so small? im not good with codes so i can't review.

**Comment by voxrie** [comment]
is this project based on webview or something like that?

**Comment by prateek-chaubey** [comment]
Yes it's based on webview.

**Comment by voxrie** [comment]
![resim](https://user-images.githubusercontent.com/64368231/165430471-2d800e3e-a32e-4fe1-8a7e-018c371205dd.png)

**Comment by prateek-chaubey** [comment]
Android Version?

**Comment by voxrie** [comment]
Android 7
