### ISSUE TITLE
Bugs/Suggestions.

### ISSUE THREAD

**Issue by Insane0828** [prateek-chaubey/YTPro#10]
Hii,

Bug: After turning "ambient mode" off. It turns on automatically after playing other video.

Suggestions: The sound quality is very bad, specially not good for listening music. If possible please improve the sound quality of videos, i know that it's a web version but please try ;)

**Comment by prateek-chaubey** [comment]
I have added the `force dark` mode , probably this can be the reason for that.

You mean the sound quality in `BG PLAY` ?

**Comment by Insane0828** [comment]
Not only in bg play. The sound quality isn't good.

**Comment by prateek-chaubey** [comment]
Can you add some sort of sample comparison.
Also i guess this is due to web version of YouTube
