### ISSUE TITLE
Adblock

### ISSUE THREAD

**Issue by senolfndk** [prateek-chaubey/YTPro#11]
Can you add ad blocking feature?

**Comment by prateek-chaubey** [comment]
Can you provide some more details regarding that

**Comment by senolfndk** [comment]
Ads appear while watching video

**Comment by senolfndk** [comment]
addition

**Comment by prateek-chaubey** [comment]
I can't completely remove the ads but i can skip them , if you have any method for completely removing them.

Please share it as it would be helpful

**Comment by senolfndk** [comment]
> Reklamları tamamen kaldıramıyorum ancak reklamları tamamen kaldırmak için herhangi bir yönteminiz varsa atlayabilirim.
> 
> Faydalı olacağı için lütfen paylaşın

I'm not an expert on this subject
