### ISSUE TITLE
Can't install on xiaomi redmi note 5, miui 10

### ISSUE THREAD

**Issue by Hekermen** [prateek-chaubey/YTPro#13]
I get "There was a problem while parsing the package." To my understanding, it's because it's a different cpu architecture. App works fine on samsung and others... Xiaomi sucks for this.

**Comment by prateek-chaubey** [comment]
And you tell me the Android version of your phone.
Also if you have already installed YT PRO try uninstalling it before installing the new version.

**Comment by Hekermen** [comment]
Android 9 PKQ1.180904.001
MIUI Global 10.3.1.0 (PEIMIXM)

I can't install it at all on this xiaomi redmi 5 phone. It just gives the error. I tried googling solutions, disabling miui optimizations, but error persists.

**Comment by prateek-chaubey** [comment]
I have lowered the sdk version, now you can install it on those phones
