### ISSUE TITLE
Display bitrate, format for Audio downloads.

### ISSUE THREAD

**Issue by adithyaamara** [prateek-chaubey/YTPro#23]
@prateek-chaubey Just Like video download button shows 720p, 360P. Please show bitrate of audio also (Like 128kbps, 360kbps).
As only showing size is creating confusion what to choose.

Also It would be added advantage if video, audio buttons shows download format. (Like mp4, mp3, wav etc.,)

PS: The app you have created is amazing, Great work. Sometimes I cant even differentiate between yours, actual you-tube app.

Thank you.

**Comment by prateek-chaubey** [comment]
Sure i have been noting down the recommend features, and will implement them whenever possible. Thanks for your feedback <3

**Comment by prateek-chaubey** [comment]
Pushed [@3.3.42](https://www.npmjs.com/package/ytpro)
