### ISSUE TITLE
Background player

### ISSUE THREAD

**Issue by Mohamedbg23** [prateek-chaubey/YTPro#25]
I don't know if it's a real issue or not available feature.
So basically when your turn the bg player you should see in the notification bar the youtube player like spotify.

**Comment by Mohamedbg23** [comment]
Another big issue the bg video player after a while of 5 min playing the audio start to broke somethint i can describe with like a pause and play the audio unless you return the application so it will back normal then if left the app and close your phone and keep listening the issue won't stop and you need to repeat the cycle so you can listen normally.

**Comment by prateek-chaubey** [comment]
This issue is related with #19

**Comment by prateek-chaubey** [comment]
Updated the app in the latest release [v3.4](https://github.com/prateek-chaubey/YTPro/releases/tag/v3.4)
