### ISSUE TITLE
Downloading To Local Device

### ISSUE THREAD

**Issue by naveedsalik** [prateek-chaubey/YTPro#3]
hi Sir! I like your work. Its really a new art for YouTube.
I am facing the issue in downloading the video. when the download is completed the video can't stored in my local device. How can I solve this issue?

Thanks in advance.

**Comment by prateek-chaubey** [comment]
Hello there,
YT Pro uses Download Manager to download videos.
It depends upon your Download Manager where it saves the file, sometimes the downloaded videos and images aren't shown in gallery when downloaded through Download Manager.(specifically in chinese devices).
After downloading the video try finding it in Download Manager App.

**Comment by naveedsalik** [comment]
Thank your for your timely response..
