### ISSUE TITLE
download feature not working

### ISSUE THREAD

**Issue by MadameVerre** [prateek-chaubey/YTPro#34]
I have tried downloading various videos but it doesn't work.
Phone oppo f1s android 6.0
![Screenshot_2024-04-11-02-24-09-18](https://github.com/prateek-chaubey/YTPro/assets/159318915/c31aaa90-d097-4229-973b-94ba8eca0577)

**Comment by prateek-chaubey** [comment]
Looks like we need Storage Permission in order to download the file in the lower Android versions.

I will update the app soon , with this patch.

**Comment by prateek-chaubey** [comment]
Updated the app in the latest release [v3.4](https://github.com/prateek-chaubey/YTPro/releases/tag/v3.4)
