### ISSUE TITLE
stop play back

### ISSUE THREAD

**Issue by hammer-boy** [prateek-chaubey/YTPro#36]
YouTube vanced ver 19.11.43 stop playing after few seconds

**Comment by prateek-chaubey** [comment]
You mean the background player?

**Comment by hammer-boy** [comment]
no normal player even dow

**Comment by Gariibi** [comment]
Facing the same issue and we cannot connect with the creator of vanced I am also facing same issue from 2 may

**Comment by prateek-chaubey** [comment]
Updated the app in the latest release [v3.4](https://github.com/prateek-chaubey/YTPro/releases/tag/v3.4)
