### ISSUE TITLE
Download video not showing in file 

### ISSUE THREAD

**Issue by Vivekmasona** [prateek-chaubey/YTPro#4]
Video download krne par show nhi ho raha kahi par bhi na file me na player me or MP3 download add kijiye 

Baki youtube bahut badhiya hai lite hai cool features

**Comment by prateek-chaubey** [comment]
Probably this can be the issue.
#3

**Comment by Vivekmasona** [comment]
Bhai solve kr do
Me esi ko use krta hu

**Comment by Vivekmasona** [comment]
Sir jald hi update dijiye kyu ki me es ytpro ka use karta hu 
So jaldi kijiye

**Comment by Vivekmasona** [comment]
Sir MP3 download bhi add kr dijiyega.

**Comment by Vivekmasona** [comment]
And background music is closed in some time later please solve thi issues
