### ISSUE TITLE
Background play option & Downlod Error 

### ISSUE THREAD

**Issue by Saman-Pushpa-Kumara** [prateek-chaubey/YTPro#40]
01.
Bg play is turned on and then the screen is turned off and the music plays fine. But after **2 to 3 minutes it auto stops**.
It repeats itself..

Tried turning off battery optimize.. but the error is coming..
Would you please fix it…

02.
Download option error
**Not download popular** international video. But the locally video is **downloaded..**

Will that error also be processed...?

**Comment by prateek-chaubey** [comment]
1. BGPlay is still in development, it will be updated in the next release 
2. Can you give a few examples of the videos that aren't getting downloaded

**Comment by Saman-Pushpa-Kumara** [comment]
.2
not download ex:
https://youtu.be/xFutjZEBTXs?si=d3F700SVI_6Xjm1m

https://youtu.be/CevxZvSJLk8?si=0JOKxNkc17huf63f

**Comment by Saman-Pushpa-Kumara** [comment]
This is a very simple and good application. Thank you very much.

When will you release your next update..?
(Can you tell me a near date)

**Comment by prateek-chaubey** [comment]
I checked the details u provided above 
It's working perfectly in my case.


Also it used the api endpoint of 
https://youtube-downloader.deno.dev

Check if it's working in your case.

**Comment by Saman-Pushpa-Kumara** [comment]
Can you fix the fact that the background play is turned off only..?
Or are you trying to play the background through the choice player or default player..?

**Comment by prateek-chaubey** [comment]
Currently i have been busy in few of my other works
I shall be updating it when i am totally free

**Comment by prateek-chaubey** [comment]
Updated the app in the latest release [v3.4](https://github.com/prateek-chaubey/YTPro/releases/tag/v3.4)
