### ISSUE TITLE
Background Play

### ISSUE THREAD

**Issue by annonymousmare** [prateek-chaubey/YTPro#43]
I have issues with background play.
1. When i minimize the app it only go to pip not background play.
2. After clicking on Bg play button its take time to did that.
3. I am unable to play a playlist in bg play, it stop after 1 song i have to again open it.

**Comment by prateek-chaubey** [comment]
1. When you press the home button , the default configuration is PIP Mode
2. It takes time to go to BG as it wait for the song to be loaded
3. BG Play  is still in development , it will take some time to update it.

**Comment by prateek-chaubey** [comment]
Updated the app in the latest release [v3.4](https://github.com/prateek-chaubey/YTPro/releases/tag/v3.4)
