### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by yqk100** [prateek-chaubey/YTPro#47]
![Screenshot_2024-07-04-23-24-55-33_2b498b5ca651952f33ef39d01aa0f41c](https://github.com/prateek-chaubey/YTPro/assets/13610251/51593218-4322-4bd4-9d52-b64bc1edec48)

**Comment by prateek-chaubey** [comment]
Yeah it was a UI glitch , please tap on `Check for Updates` it will fix the glitch
