### ISSUE TITLE
Download /Background Audio Player

### ISSUE THREAD

**Issue by l337w0rm** [prateek-chaubey/YTPro#49]
Hi there
Downloads not working (Couldn't dowload items)
Bg Aplayer not  working
Device xiaomi redmi 13c

**Comment by prateek-chaubey** [comment]
Yeah i have facing the same issue since yesterday, i debugged real quick and found that , YouTube has updated the code for deciphering the videos.
So now we need new methods for that , i am waiting for `node-ytdl` to update the code , as the download and background play both uses its method to get the video formats.

**Comment by harshpandita2000** [comment]
can you add feature of play in background

**Comment by prateek-chaubey** [comment]
Background player is working once again.
The Download button will be patched soon as well

**Comment by madmaus-070** [comment]
> Background player is working once again. The Download button will be patched soon as well

Any idea when it can be fixed? 
We will be going on holiday and i want to download a few movies for my son.
Would be much appreciated.

**Comment by prateek-chaubey** [comment]
An update has been published , the changes will be reflected soon.
Try clicking on `Check for Updates` button to make it quicker.

**Comment by l337w0rm** [comment]
hi
download is not working :/

**Comment by madmaus-070** [comment]
Nope for also on 3.45

**Comment by prateek-chaubey** [comment]
I have already pushed the [commit](https://github.com/prateek-chaubey/YTPro/commit/9e1526a15fd40a548775b136a498611523925567)
I think the CDN takes a bit of time to reflect the changes. I hope it updates it quickly.

**Comment by madmaus-070** [comment]
> I have already pushed the [commit](https://github.com/prateek-chaubey/YTPro/commit/9e1526a15fd40a548775b136a498611523925567) I think the CDN takes a bit of time to reflect the changes. I hope it updates it quickly.

Not sure what you mean but i downloaded the newest version 3.45 and downloading still give an error downloading failed.

**Comment by prateek-chaubey** [comment]
Click on `Check for Updates` , the CDN has updated the code.
The features will be working right away
