### ISSUE TITLE
Bhai kab tak update milega 

### ISSUE THREAD

**Issue by Vivekmasona** [prateek-chaubey/YTPro#5]
Kab tak downloading issues solve hoga

**Comment by prateek-chaubey** [comment]
As i have mentioned earlier there isn't any issue in downloading.
It depends upon your Download Manager where it saves the file.
Try checking the video through your downloads manager.

**Comment by Vivekmasona** [comment]
Bhai sab phone ke sath ho raha hai mene khud oppo Vivo redmi samsung sab me
cheak kr liye
Video download ho raha hai but file me kahi nhi mil raha

**Comment by prateek-chaubey** [comment]
Can you record a video showing the steps you have tried.
It will be very helpful in fixing the issue.

**Comment by Vivekmasona** [comment]
Ok. Bro

**Comment by Vivekmasona** [comment]
Bhai mene video bana diya `https://youtu.be/DZCypwOHKmQ`

**Comment by prateek-chaubey** [comment]
![Download Manager](https://user-images.githubusercontent.com/41151614/194008215-9313a969-4f05-475f-963a-b54683b3e8b2.jpg)

The video that you have downloaded can be found in this app. Whereas I shall be improving the Downloads Feature in next update

**Comment by Vivekmasona** [comment]
Downloads app mi ka hai or mere phone realme Narzo 20 pro hai  mere phone me ye downloads app ka package mach ho raha hai  or install nhi ho ra

**Comment by Vivekmasona** [comment]
Bhai yrr download video file me nhi aa raha  yrr solv kr do ya website prefer kr do jis ki kisi website pe ja ke download ho sake

**Comment by Afaqkhan16b** [comment]
Hii

**Comment by Afaqkhan16b** [comment]
Plz I need Instagram hack command

**Comment by Afaqkhan16b** [comment]
@prateek-chaubey hii I need Instagram hack command
