### ISSUE TITLE
Download eror.

### ISSUE THREAD

**Issue by Robertoken** [prateek-chaubey/YTPro#51]
{
  "ns": "yt",
  "el": "detailpage",
  "cpn": "F8CL81vX26kCIUMY",
  "ver": 2,
  "cmt": "9.584",
  "fmt": "243",
  "fs": "0",
  "rt": "10.066",
  "euri": "",
  "lact": 1,
  "cl": "653439333",
  "mos": 0,
  "state": "8",
  "volume": 100,
  "cbrand": "samsung",
  "cbr": "Chrome Mobile Webview",
  "cbrver": "126.0.6478.134",
  "c": "MWEB",
  "cver": "2.20240722.00.00",
  "cplayer": "UNIPLAYER",
  "cmodel": "sm-s908b",
  "cos": "Android",
  "cosver": "14",
  "cplatform": "MOBILE",
  "hl": "ro_RO",
  "cr": "NL",
  "len": "179.601",
  "fexp": "v1,24004644,434717,127326,26443548,7111,24166,12177,9954,1192,26496,4147,2819,2,17768,29151,2197,9996,1103,6953,101,8440,2503,581,1890,6008,1538,3298,9367,1376,3760,12945,5699,2464,2443,322,147,3,2125,15,1322,50,4154,2382,337,2292,2912",
  "afmt": "251",
  "muted": "0",
  "conn": "1",
  "docid": "C_BOFKTvnkE",
  "ei": "lC-fZuSCLLK06dsP7Z-BoQI",
  "plid": "AAYd4nvHTGXdEQAF",
  "referrer": "https://m.youtube.com/",
  "sdetail": "p:m.youtube.com/",
  "sourceid": "r",
  "list": "PLc25XffDlYpfT34Hj_EZUpqoHdMLX28QI",
  "of": "GboE2cNcy70lyJDTWpN6bg",
  "vm": "CAIQARgEOjJBSHFpSlRLS1dMTmdKYXgwX2xNRGxPUmN1NE1fbVJQUW1JNUlaNkN5NXIwekJETmF1d2JaQU9BckJGc2c3eEcwODJueEVVM3dZVnZ5Sm9uVzlTdl9pTlBmUVJUT2tjaG1TN1lweU50UWJvRTZqVVhldmhWa043dkktcjJSSkJIQ1p0QlB0SkdjRVRtNldnuAEB",
  "vct": "9.584",
  "vd": "179.601",
  "vpl": "0.000-9.584",
  "vbu": "0.000-45.599",
  "vbs": "0.000-179.601",
  "vpa": "0",
  "vsk": "0",
  "ven": "0",
  "vpr": "1",
  "vrs": "4",
  "vns": "2",
  "vec": "null",
  "vemsg": "",
  "vvol": "1",
  "vdom": "1",
  "vsrc": "1",
  "vw": "384",
  "vh": "216",
  "lct": "9.550",
  "lsk": false,
  "lmf": false,
  "lbw": "1373399.446",
  "lhd": "0.084",
  "lst": "0.000",
  "laa": "itag_251_type_3_src_reslicegetRequestInfoForRange_segsrc_reslicegetRequestInfoForRange_seg_4_range_664959-827018_time_40.0-50.0_off_0_len_162060_end_1",
  "lva": "itag_243_type_3_src_reslicegetRequestInfoForRange_segsrc_reslicegetRequestInfoForRange_seg_8_range_1367368-1527030_time_40.5-45.6_off_0_len_159663_end_1",
  "lar": "itag_251_type_3_src_getRequestInfoForRange_segsrc_getRequestInfoForRange_seg_4_range_664959-827018_time_40.0-50.0_off_0_len_162060_end_1",
  "lvr": "itag_243_type_3_src_getRequestInfoForRange_segsrc_getRequestInfoForRange_seg_8_range_1367368-1527030_time_40.5-45.6_off_0_len_159663_end_1",
  "laq": "0",
  "lvq": "0",
  "lab": "0.000-50.001",
  "lvb": "0.000-45.599",
  "ismb": 11420000,
  "playerResponseCpn": "pnuydntWcqu9T3rm",
  "relative_loudness": "3.380",
  "optimal_format": "360p",
  "user_qual": 0,
  "release_version": "youtube.player.web_20240717_01_RC00",
  "debug_videoId": "C_BOFKTvnkE",
  "0sz": "false",
  "op": "",
  "yof": "false",
  "dis": "",
  "gpu": "ANGLE_(Samsung_Xclipse_920)_on_Vulkan_1.3.231",
  "ps": "blazer",
  "webview": 1,
  "debug_playbackQuality": "medium",
  "debug_date": "Tue Jul 23 2024 06:20:54 GMT+0200 (Ora de vară a Europei Centrale)",
  "origin": "https://m.youtube.com",
  "timestamp": 1721708454509
}

**Comment by prateek-chaubey** [comment]
Is it still not working right now?

**Comment by prateek-chaubey** [comment]
I have pushed an update, it will be fixed soon
