### ISSUE TITLE
Download 

### ISSUE THREAD

**Issue by OHURU-IAN** [prateek-chaubey/YTPro#52]
I can't download videos and audios from here

**Comment by prateek-chaubey** [comment]
Just checked now , it's working perfectly.
Can you share more information regarding the error.

**Comment by OHURU-IAN** [comment]
Its working perfectly, thank you

**Comment by OHURU-IAN** [comment]
The problem has come back again

**Comment by prateek-chaubey** [comment]
I have already pushed an update and it have been fixed , click on `Check for Updates ` in YTPRO Settings and it will be reflected in your app as well.

**Comment by OHURU-IAN** [comment]
It is now working, thanks a lot
