### ISSUE TITLE
Add the Light mode themes features in youtube pro

### ISSUE THREAD

**Issue by ihackyou42** [prateek-chaubey/YTPro#54]

**Comment by prateek-chaubey** [comment]
Did someone say light mode?
<img src=https://media.tenor.com/4__zAqLYkegAAAAM/light-blind.gif >

**Comment by prateek-chaubey** [comment]
Done

**Comment by prateek-chaubey** [comment]
Force Dark  mode has been removed , but still it needs updation of YouTube Pro elements which will be updated soon
