### ISSUE TITLE
Download is not working

### ISSUE THREAD

**Issue by danil4u** [prateek-chaubey/YTPro#55]
Hi, 
    Download is not working it seems, can you please check once.

thank you

**Comment by prateek-chaubey** [comment]
Youtube has been continuously updating the ncode , that's why the issue has been occuring frequently

**Comment by danil4u** [comment]
thank you for the quick response, will be waiting for the update with the fix

**Comment by Dapgee** [comment]
Download issue persistence can we have any update in a positive way please

**Comment by Dapgee** [comment]
A great application any time line on fix update

**Comment by danil4u** [comment]
thank you for the update, it is working now.
