### ISSUE TITLE
YTPro doesn't work 

### ISSUE THREAD

**Issue by claudiomele78** [prateek-chaubey/YTPro#57]
YTPro no longer works, the download buttons have disappeared and so have the others...

**Comment by Vaibhav-Sharma010204** [comment]
@prateek-chaubey 
The additional features are not working, working like just a regular YouTube app .
Do something needful

Thanking in advance

**Comment by mobassir94** [comment]
Ads are not getting blocked. Any solution please?

**Comment by prateek-chaubey** [comment]
Youtube got updated and now it blocks all the external scripts and html injected to it.
I am searching for a workaround , will update the app soon.

**Comment by prateek-chaubey** [comment]
Has been patched in the latest release, please update your app.
