### ISSUE TITLE
Download is not working on real Android Devices

### ISSUE THREAD

**Issue by danil4u** [prateek-chaubey/YTPro#63]
Hi
   Thank you for the nice project and regular updates.

It seems download is not working on real Android devices, tried to run this project on different devices and it is returning url as "undefined" but it returns the correct url on the Android simulator like "Pixel Fold API 35". Can you Please look into it.

thank you

**Comment by prateek-chaubey** [comment]
Basically YouTube has been playing with it's code and now it's getting harder to extract the playback url of the videos , i have been regularly updating the code, but I can't be much fast to update it instantly.

I think we have to suffer from this until and unless we get a proper solution.
I will be pushing the code with latest extraction function, it will be reflected in the YTPRO after some time.

**Comment by danil4u** [comment]
Yes thank you for all your efforts, but interestingly it works on Android Simulator, not sure may be something related to cookies or so.

**Comment by danil4u** [comment]
issues is got resolved with the latest changes, thank you and appreciate all your efforts.
