### ISSUE TITLE
[Feature] Support to open web pages in the browser that comes with the phone

### ISSUE THREAD

**Issue by muyiacc** [prateek-chaubey/YTPro#68]
Support to open web pages in the browser that comes with the phone.

**Comment by yuipp** [comment]
And what browser used on default?

**Comment by muyiacc** [comment]
firefox

**Comment by muyiacc** [comment]
This situation is sometimes when a webpage needs to be opened and the URL needs to be saved, but the URL cannot be seen, so it is difficult to save the URL.

**Comment by yuipp** [comment]
W not use share option?

**Comment by muyiacc** [comment]
![S41104-09282808_com google android youtube pro](https://github.com/user-attachments/assets/3015560c-24cd-4b61-a3b0-d562522e8f47)
