### ISSUE TITLE
Security Blocked by Google Play Protect

### ISSUE THREAD

**Issue by Ramim256** [prateek-chaubey/YTPro#7]
![image](https://user-images.githubusercontent.com/20925210/213294814-f74a7c24-eba2-46f9-810d-aba0269201ad.png)
![image](https://user-images.githubusercontent.com/20925210/213294907-883ec256-8dad-4786-a3ad-db2e7fb110aa.png)
![image](https://user-images.githubusercontent.com/20925210/213294996-730840fd-f155-41ba-8019-b2d7d72f68bf.png)
![image](https://user-images.githubusercontent.com/20925210/213295043-65a2e03e-5935-42ff-93af-44cf949d2bdb.png)

**Comment by prateek-chaubey** [comment]
Those are False Positive detections.
Idk why it's marked as virus.
Whereas the source code is available publicly, you can compile them yourselves if you don't trust the apk provided on ReadMe page.
