### ISSUE TITLE
Share function 

### ISSUE THREAD

**Issue by yuipp** [prateek-chaubey/YTPro#71]
Share function not working properly - just empty link, in regular browser ok, can you fix it please? Android 14. Thx

broke recently, it was ok before

**Comment by prateek-chaubey** [comment]
Can you share some screenshots

**Comment by yuipp** [comment]
screenshot 
![Screenshot_20241025-095618_YouTube Pro](https://github.com/user-attachments/assets/c83b9b25-9b50-4268-b57e-337e3e1d2d82)

**Comment by yuipp** [comment]
After ota my phone - now it's ok, so close this issue
