### ISSUE TITLE
Chat option not showing 

### ISSUE THREAD

**Issue by cyberxaman** [prateek-chaubey/YTPro#8]
Chat option not showing during watching live stream

**Comment by prateek-chaubey** [comment]
Can you provide more information regarding the issue.
1. Livestream link
2. Screenshot of the bug
3. Expected behaviour

**Comment by prateek-chaubey** [comment]
So i guess youtube doesn't show chat option on it's mobile web version.

**Comment by prateek-chaubey** [comment]
https://stackoverflow.com/questions/55665525/youtube-live-chat-show-only-on-desktop-on-mobile-see-nothing
